window:
  # Window dimensions in character columns and lines
  # Falls back to size specified by window manager if set to 0x0.
  # (changes require restart)
  dimensions:
    columns: 160
    lines: 50

font:
  size: 9

  normal:
    family: CozetteVector
    style: Regular

  bold:
    family: CozetteVector
    style: Regular

  italic:
    family: CozetteVector
    style: Regular

  bold_italic:
    family: CozetteVector
    style: Regular
